### ISSUE TITLE
Multi-Cloud

### ISSUE THREAD

**Issue by msohn** [msohn/issues#4]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:43 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/11_

----

# Stories
* As provider I want to provision on AWS, Azure and GCP, so that Kubernetes runs in the Public Hyper-Scale Clouds where our customers already have their footprint.
* As provider I want to provision on OpenStack and Bare Metal, so that Kubernetes runs in our SAP DCs for data privacy reasons.

# Motivation
We shall go where our customers are, i.e. multi-cloud and also our own SAP DCs for data privacy reasons. We shall offer this in an operator-friendly way with simplified operations.

# Acceptance Criteria
Clusters can be created, operated and destroyed (following the seed & shoot cluster approach):
- [x] Kubernetes on AWS (covering the same functionality as our kops-based solution)
- [ ] Kubernetes on Azure to (almost) the same extent as we have it on AWS
- [ ] Kubernetes on GCP to (almost) the same extent as we have it on AWS
- [ ] Kubernetes on OpenStack to (almost) the same extent as we have it on AWS
- [ ] Later: Kubernetes on Bare Metal to (almost) the same extent as we have it on AWS

# Open Question
Should we rely on Stefan Vetter from GLDS (who has a very bad reputation from everybody who worked together with him as he is promising more than he delivered in the past) or buy a distribution like https://coreos.com/tectonic/ that is already available on the market?

:information_source: Migrated and merged with from Jira issue [KUBE-85](https://jtrack.removed/browse/KUBE-85) and  [KUBE-82](https://jtrack.removed/browse/KUBE-82)
